language: android
android:
  components:
    # The BuildTools version used by your project
    - build-tools-19.1.0
    # The SDK version used to compile your project
    - android-22

node_js:
  - 6.10.1


sudo: false

branches:
  only:
  - master

install:
  - npm install -g cordova

before_script:
  - cordova platform add android

script:
  - cordova prepare
  
release:
  - exit 0  
