language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-19.1.0

    # The SDK version used to compile your project
    - android-22

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-22
    - sys-img-armeabi-v7a-android-17

node_js:
  - 6.10.1


sudo: false

branches:
  only:
  - master

install:
  - npm install
  - npm install -g cordova

before_script:
  - cordova platform add android

script:
  - cordova prepare
  - cordova build android
  
release:
  - exit 0  
