language: android
android:
  components:
    # The BuildTools version used by your project
    #- build-tools-19.1.0
    # The SDK version used to compile your project
    #- android-22

node_js:
  - 4.4.7

branches:
  only:
  - master

install:
  - npm install -g cordova

before_script:
  - node -v

script:
  - cordova -v
  
release:
  - exit 0  
