language: node_js
#android:
 # components:
    # The BuildTools version used by your project
    #- build-tools-19.1.0
    # The SDK version used to compile your project
    #- android-22

node_js:
  - "6"
  
install:
  - npm install -g cordova
  - cordova platform add browser

before_script:
  - node --version

script:
 - cordova prepare
  
release:
  - exit 0  
